LPlus/src/LPlus/Areas/AccountManagement/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Server.Server.User;
using Model.User;
using Common.Helper;

namespace LPlus.Controllers
{
    [Area("AccountManagement")]
    [AllowAnonymous]
    public class AccountController : Controller
    {
        private readonly UserManager<UserModel> _userManager;
        private readonly IUserServer _userServer;
        public AccountController(UserManager<UserModel> userManager, IUserServer userServer)
        {
            _userManager = userManager;
            _userServer = userServer;
        }
        public IActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            UserModel model = new UserModel();
            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserModel model, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                bool result = await _userServer.CheckPasswordAsync(model);
                if (result)
                {
                    var user = await _userManager.FindByNameAsync(model.Account);
                    if (user != null)
                    {
                        await UserHelper.SignInAsync(user, model.RememberMe, HttpContext);
                        if (Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }

            }
            ModelState.AddModelError("Account", "Account is error or Password is error");
            ModelState.AddModelError("Email", "");
            return View(model);
        }
        [HttpGet]
        public IActionResult Register()
        {
            UserModel model = new UserModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(UserModel model)
        {
            ValidateModel(model);
            if (ModelState.IsValid)
            {
                var result = await _userManager.CreateAsync(model);
                if (result.Succeeded)
                {
                    await UserHelper.SignInAsync(model, model.RememberMe, HttpContext);
                    return RedirectToAction(nameof(HomeController.Index), "Home",new { area=""});
                }
                ModelState.AddModelError("", result.Errors.ToString());
            }
            return View(model);
        }


        private void ValidateModel(UserModel model)
        {
            if (!model.Password.Equals(model.EncryptPassword))
            {
                ModelState.AddModelError("", "输入的两次密码不相同。");
            }
        }

        public IActionResult Forbidden()
        {
            return View();
        }
        public async Task<IActionResult> SignOut()
        {
            await UserHelper.SignOutAsync(HttpContext);
            return Redirect("~/");
        }
        public IActionResult TestPage()
        {
            return View();
        }
    }
}

LPlus/src/LPlus/Areas/Web/Controllers/NoteController.cs
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Model.Note;
using Server.Server.Note;
using Model.Comment;
using System.Threading.Tasks;
using Common.Helper;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace LPlus.Areas.Web.Controllers
{
    [Area("Web")]
    public class NoteController : Controller
    {
        private INoteServer _server;
        public NoteController(INoteServer server)
        {
            _server = server;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<NoteModel> data = _server.GetNotes(pageIndex:0);
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> PostComment(CommentModel comment)
        {
            comment.UserPicture = UserHelper.GetUserPicture(HttpContext);
            comment.UserID = UserHelper.GetUserID(HttpContext);
            await _server.PostCommentAsync(comment);
            return PartialView("_Comment",comment);
        }
        [HttpPost]
        public async Task<IActionResult> PublishNote(NoteModel note)
        {
            note.UserPicture = UserHelper.GetUserPicture(HttpContext);
            note.UserID = UserHelper.GetUserID(HttpContext);
            await _server.PublishNoteAsync(note);
            List<NoteModel> data = _server.GetNotes(pageIndex: 0);
            return PartialView("_Note", data);
        }
        public async Task LikeCount(int noteID)
        {
            await _server.LikeCountAsync(noteID);
        }
        public async Task DeleteComment(int commentID)
        {
            await _server.DeleteCommentAsync(commentID);
        }
        public IActionResult GetNotes(int pageIndex)
        {
            List<NoteModel> data = _server.GetNotes(pageIndex);
            if(data.Count()>0)
            {
                var datas = data.OrderByDescending(o => o.CreateDate).GroupBy(i => i.CreateDate.Date);
                return PartialView("_TimeLineData", datas);
            }
            return Content("NULL");
        }
    }
}

LPlus/src/LPlus/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LPlus.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

LPlus/src/LPlus/ViewComponents/ContactListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Model.User;
using Server.Server.User;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace LPlus.ViewComponents
{
    public class ContactListViewComponent:ViewComponent
    {
        private IUserServer _userServer { get; set; }
        public ContactListViewComponent(IUserServer userServer)
        {
            _userServer = userServer;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //string UserName = User.Identity.IsAuthenticated ? User.Identity.Name: string.Empty;
            string UserID = HttpContext.User.FindFirst("UserID").Value;
            //string UserName = User.Identities.First().IsAuthenticated ? User.Identities.First(u => u.IsAuthenticated).FindFirst(ClaimTypes.Name).Value : string.Empty;
            IEnumerable<UserModel> userList = new List<UserModel>();
            userList = await _userServer.GetContactList(Convert.ToInt32(UserID));
            return await Task.Run<IViewComponentResult>(() => { return View(userList); });
        }
    }
}

LPlus/src/LPlus/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Server.Server.Menu;
using System.Threading.Tasks;

namespace LPlus.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private IMenuServer _menuServer { get; set; }
        public MenuViewComponent(IMenuServer menuServer)
        {
            _menuServer = menuServer;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var menus = _menuServer.GetMenus();
            return await Task.Run<IViewComponentResult>(() => { return View(menus); });
        }
    }
}

LPlus/src/LPlus/Areas/AccountManagement/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="shortcut icon" href="../images/favicon.png" type="image/png">-->
    <link rel="shortcut icon icon" href="~/images/lexitron.png"/>
    <link rel="stylesheet" href="~/css/quirk/font-awesome.css">
    <link rel="stylesheet" href="~/css/quirk/quirk.css"> 
    <link rel="stylesheet" href="~/css/quirk/select2.css">   
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../lib/html5shiv/html5shiv.js"></script>
    <script src="../lib/respond/respond.src.js"></script>
    <![endif]-->
</head>
<body class="signwrapper">
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/quirk/modernizr.js"></script>
        <script src="~/lib/quirk/select2.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
        <script src="~/lib/quirk/modernizr.js">
        </script>
        <script src="~/lib/quirk/modernizr.js"></script>
        <script src="~/lib/quirk/select2.js"></script>
    </environment>


    @RenderBody()
</body>
</html>

LPlus/src/LPlus/Areas/Web/Views/Note/Index.cshtml
@using Model.Note
@using Common.Helper
@using Microsoft.AspNetCore.Http
@model List<NoteModel>

@inject IHttpContextAccessor context

<link rel="stylesheet" href="~/css/comment/myemojiPl.css"/>
<script type="text/javascript" src="~/lib/comment/myemojiPl.js"></script>
<ol class="breadcrumb breadcrumb-quirk">
    <li><a asp-action="index" asp-controller="home"><i class="fa fa-home mr5"></i> 主页</a></li>
    <li><a href="buttons.html">测试功能</a></li>
    <li class="active">好友圈</li>
</ol>
<hr class="darken">
<div class="row">
    <div class="col-sm-8 col-md-9 col-lg-10">
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img alt="" src="@UserHelper.GetUserPicture(context.HttpContext)" class="media-object img-circle UserPicture">
                </a>
            </div>
            <div class="media-body">
                @Html.Partial("_CommentPublish", "PublishComment")
            </div>
        </div><!-- media -->
        
        <br />
        <div class="timeline-wrapper">
            @Html.Partial("_Note",Model)
            <div class="timeline-date"><a onclick="loadMore()" style="cursor:pointer;" id="loadMore">Load more...</a></div>
        </div><!-- timeline-wrapper -->
    </div>
</div><!-- row -->
<input type="hidden" id="pageIndex" value="0"/>
<script type="text/javascript">
    var loadMore=function()
    {
        var pageIndex = parseInt($("#pageIndex").val()) + 1;
        $("#pageIndex").val(pageIndex);
        var url = "@Url.Action("GetNotes", "Note","Web")" + "&pageIndex=" + pageIndex;
        ajaxMethod.get(url, "", function (result) {
            if (result == "NULL")
            {
                $("#loadMore").html("NULL");
            }
            else
            {
                $("#timeline-data").append(result);
            }            
        });
    }
</script>

LPlus/src/LPlus/Areas/Web/Views/Note/_Comment.cshtml
@using Model.Comment;
@model CommentModel
<li class="media" id="media-@Model.ID">
    <div class="media-left">
        <a href="#">
            <img class="media-object img-circle" src="@Model.UserPicture" alt="">
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading">@Model.CreateBy<small>@Model.CreateDate</small></h4>
        @Html.Raw(Model.Content)

    </div>
    <div class="media-right">
        <a class="glyphicon glyphicon-remove" onclick="deleteComment(@Model.ID,@Model.NoteID)"></a>
    </div>
</li>

LPlus/src/LPlus/Areas/Web/Views/Note/_Note.cshtml
@using Model.Note
@using System.Security.Claims
@using Common.Helper
@model List<NoteModel>
@{
    var datas = Model.OrderByDescending(o => o.CreateDate).GroupBy(i => i.CreateDate.Date);
    string UserName = User.Identities.First().IsAuthenticated ? User.Identities.First(u => u.IsAuthenticated).FindFirst(ClaimTypes.Name).Value : "游客";
}

@if (Model != null && Model.Count() > 0)
{
    <div id="timeline-data">
        @Html.Partial("_TimeLineData", datas)
        </div>
        <form id="commentData">
            <input type="hidden" id="CreateBy" name="CreateBy" value="@UserName" />
            <input type="hidden" id="Content" name="Content" />
            <input type="hidden" id="NoteID" name="NoteID" />
            <input type="hidden" id="Address" name="Address" />
        </form>
        }
        @Html.Partial("_CommentJS")
        <script type="text/javascript">

            function getNowFormatDate() {
                var date = new Date();
                var seperator1 = "/";
                var seperator2 = ":";
                var month = date.getMonth() + 1;
                var strDate = date.getDate();
                var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate
                        + " " + date.getHours() + seperator2 + date.getMinutes()
                        + seperator2 + date.getSeconds();
                return currentdate;
            }
            var writeComment = function (id) {
                if ($("#Input_text-" + id).html() != null && $("#Input_text-" + id).html() != "") {
                    $("#Content").val($("#Input_text-" + id).html());
                    $("#NoteID").val(id);
                    var data = $("#commentData").serialize();
                    var url = "@Url.Action("PostComment", "Note","Web")";
                    ajaxMethod.post(url, data, function (result) {
                        var count = parseInt($("#count-" + id).html()) + 1;
                        $("#count-" + id).html(count);
                        if ($("#commentOnclick-" + id).attr("aria-expanded") == false
                            || $("#commentOnclick-" + id).attr("aria-expanded") == "false"
                            || $("#commentOnclick-" + id).attr("aria-expanded") == undefined) {
                            $("#commentOnclick-" + id).trigger("click");
                        }
                        $("#comment-" + id).find("ul").append(result);
                        $("#Input_text-" + id).html("");
                    });
                }
            }
            var like = function (id) {
                var url = "@Url.Action("LikeCount", "Note", "Web")" + "&noteID=" + id;
                ajaxMethod.get(url, "", function () {
                    var count = parseInt($("#like-" + id).html()) + 1;
                    $("#like-" + id).html(count);
                });
            }
            var deleteComment = function (id, noteID) {
                var url = "@Url.Action("DeleteComment", "Note", "Web")" + "&commentID=" + id;
                ajaxMethod.get(url, "", function () {
                    var count = parseInt($("#count-" + noteID).html()) - 1;
                    $("#count-" + noteID).html(count);
                    $(".media-list").find("#media-" + id).remove();
                });

            }
            var publishNote = function (id) {
                if ($("#Input_text-" + id).html() != null && $("#Input_text-" + id).html() != "") {
                    $("#Content").val($("#Input_text-" + id).html());
                    $("#Address").val(getLocation());
                    var data = $("#commentData").serialize();
                    var url = "@Url.Action("PublishNote", "Note","Web")";
                    ajaxMethod.post(url, data, function (result) {
                        $(".timeline-wrapper").html(result);
                    });
                }

            }

        </script>

LPlus/src/LPlus/Areas/Web/Views/Note/_TimeLineData.cshtml
@using Model.Note
@using System.Security.Claims
@using Common.Helper
@model IEnumerable<IGrouping<DateTime,NoteModel>>

@foreach (var data in Model)
{

        <div class="timeline-date">@data.FirstOrDefault().CreateDate.ToString("yyyy-MM-dd")</div>
        @foreach (var item in data)
        {
            <div class="panel panel-post-item status">
                <div class="panel-heading">
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img alt="" src="@item.UserPicture" class="media-object img-circle">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">@item.CreateBy</h4>
                            <p class="media-usermeta">
                                <span class="media-time">@item.CreateDate.ToString("HH:mm:ss")</span>
                                <i class="glyphicon glyphicon-map-marker"></i> <a>@item.Address</a>
                            </p>
                        </div>
                    </div><!-- media -->
                    <ul class="panel-options">
                        <li><a class="tooltips" href="" data-toggle="tooltip" title="View Options"><i class="glyphicon glyphicon-option-vertical"></i></a></li>
                    </ul>
                </div><!-- panel-heading -->
                <div class="panel-body">
                    @Html.Raw(item.Content)
                </div>
                <div class="panel-footer">
                    <ul class="list-inline">
                        <li><a onclick="like(@item.ID)"><i class="glyphicon glyphicon-heart"></i> Like</a></li>
                        <li>
                            <a data-target="#comment-@item.ID" data-toggle="collapse" id="commentOnclick-@item.ID">
                                <i class="glyphicon glyphicon-comment"></i> Comments (<span id="count-@item.ID">@item.Comments.CountNotNull()</span>)
                            </a>
                        </li>
                        <li class="pull-right"><span id="like-@item.ID">@item.LikeCount</span> liked this</li>
                    </ul>
                </div>
                <div class="collapse" id="comment-@item.ID">
                    <ul class="media-list">
                        @if (item.Comments != null)
                    {
                        foreach (var comment in item.Comments)
                        {
                                @Html.Partial("_Comment", comment)
                            }
                        }

                    </ul>

                </div>
                <div class="form-group">
                    @Html.Partial("_CommentBoard", item.ID.ToString())
                </div>
            </div><!-- panel panel-post -->
        }
}

LPlus/src/LPlus/Areas/Web/Views/Shared/_CommentBoard.cshtml
@model string
<div class="Main">
    <div class="Input_Box" id="Input_Box-@Model">
        <div contenteditable="true" class="Input_text rich" id="Input_text-@Model" data-placeholder="Write some comments"></div>
        @*<textarea type="" class="form-control Input_text" placeholder="Write some comments" id="commentText-@item.ID"></textarea>*@
        <div class="Input_Foot" id="Input_Foot-@Model">
            <a class="imgBtn" id="imgBtn-@Model" onclick="imgBtnClick('@Model')">'◡'</a><a class="postBtn" onclick="writeComment('@Model')">确定</a>
        </div>
    </div>
    <div class="faceDiv" id="faceDiv-@Model">
        <section class="emoji_container" id="emoji_container-@Model"></section>
        <section class="emoji_tab" id="emoji_tab-@Model"></section>
    </div>
</div>

LPlus/src/LPlus/Areas/Web/Views/Shared/_CommentJS.cshtml
<script type="text/javascript">
    var imgBtnClick = function (id) {
        var InputBox = $('#Input_Box-' + id);
        var faceDiv = $('#faceDiv-' + id);
        var InputText = InputBox.find('.Input_text');
        var emojiContainer = faceDiv.find('#emoji_container-' + id);
        if (emojiContainer.children().length <= 0) {
            faceDiv.css({
                width: Math.floor(InputText.width() / 30) * 30 + 'px',
                display: 'block'
            });
            for (var emojilist in emojiconfig) {
                emojiContainer.append('<section class="for_' + emojilist + '"></section>');
                faceDiv.find('.emoji_tab').append('<a href="#!" data-target="for_' + emojilist + '">' + emojiconfig[emojilist].name + '</a>');
                for (var i = 1; i <= emojiconfig[emojilist].maxNum; i++) {
                    if (emojiContainer.find('.for_' + emojilist) !== undefined) {
                        emojiContainer.find('.for_' + emojilist).append('<a href="#!" class="_img"><img src="' + emojiconfig[emojilist].path + i + emojiconfig[emojilist].file + '" alt="" data-alias="' + (emojiconfig[emojilist].alias == undefined ? (i + emojiconfig[emojilist].file) : emojiconfig[emojilist].alias[i]) + '" title="' + (emojiconfig[emojilist].title == undefined ? '' : emojiconfig[emojilist].title[i]) + '" /></a>');
                    }
                }
            }
            faceDiv.find('#emoji_container-' + id + ' section')[0].style.display = 'block';
            faceDiv.find('#emoji_tab-' + id + ' a')[0].className += 'active';
            faceDiv.find('#emoji_container-' + id + ' ._img').on('click', function () {
                if (InputText[0].nodeName === 'DIV') {
                    InputText.append(this.innerHTML);
                } else {
                    InputText.append('[' + $(this).find('img').attr('data-alias') + ']');
                }

            });
            faceDiv.find('.emoji_tab a').on('click', function () {
                $(this).parent().prev().find('section').hide();
                faceDiv.find('.emoji_container .' + $(this).attr('data-target')).show();
                faceDiv.find('.emoji_tab a').removeClass('active');
                this.className += ' active';
            });
        } else {
            faceDiv.toggle();
        }
    }
    var emojiconfig = {
        tieba: {
            name: "贴吧表情",
            path: "/css/comment/image/tieba/",
            maxNum: 50,
            file: ".jpg",
            placeholder: ":{alias}:",
            alias: {
                1: "hehe",
                2: "haha",
                3: "tushe",
                4: "a",
                5: "ku",
                6: "lu",
                7: "kaixin",
                8: "han",
                9: "lei",
                10: "heixian",
                11: "bishi",
                12: "bugaoxing",
                13: "zhenbang",
                14: "qian",
                15: "yiwen",
                16: "yinxian",
                17: "tu",
                18: "yi",
                19: "weiqu",
                20: "huaxin",
                21: "hu",
                22: "xiaonian",
                23: "neng",
                24: "taikaixin",
                25: "huaji",
                26: "mianqiang",
                27: "kuanghan",
                28: "guai",
                29: "shuijiao",
                30: "jinku",
                31: "shengqi",
                32: "jinya",
                33: "pen",
                34: "aixin",
                35: "xinsui",
                36: "meigui",
                37: "liwu",
                38: "caihong",
                39: "xxyl",
                40: "taiyang",
                41: "qianbi",
                42: "dnegpao",
                43: "chabei",
                44: "dangao",
                45: "yinyue",
                46: "haha2",
                47: "shenli",
                48: "damuzhi",
                49: "ruo",
                50: "OK"
            },
            title: {
                1: "呵呵",
                2: "哈哈",
                3: "吐舌",
                4: "啊",
                5: "酷",
                6: "怒",
                7: "开心",
                8: "汗",
                9: "泪",
                10: "黑线",
                11: "鄙视",
                12: "不高兴",
                13: "真棒",
                14: "钱",
                15: "疑问",
                16: "阴脸",
                17: "吐",
                18: "咦",
                19: "委屈",
                20: "花心",
                21: "呼~",
                22: "笑脸",
                23: "冷",
                24: "太开心",
                25: "滑稽",
                26: "勉强",
                27: "狂汗",
                28: "乖",
                29: "睡觉",
                30: "惊哭",
                31: "生气",
                32: "惊讶",
                33: "喷",
                34: "爱心",
                35: "心碎",
                36: "玫瑰",
                37: "礼物",
                38: "彩虹",
                39: "星星月亮",
                40: "太阳",
                41: "钱币",
                42: "灯泡",
                43: "茶杯",
                44: "蛋糕",
                45: "音乐",
                46: "haha",
                47: "胜利",
                48: "大拇指",
                49: "弱",
                50: "OK"
            }
        },
        AcFun: {
            name: "AcFun表情",
            path: "/css/comment/image/AcFun/",
            maxNum: 54,
            file: ".png"
        }
    };
    $('.Main').myEmoji({ emojiconfig: emojiconfig });
</script>

LPlus/src/LPlus/Areas/Web/Views/Shared/_CommentPublish.cshtml
@model string
<div class="Main">
    <div class="Input_Box" id="Input_Box-@Model">
        <div contenteditable="true" class="Input_text rich" id="Input_text-@Model" data-placeholder="Write some comments"></div>
        @*<textarea type="" class="form-control Input_text" placeholder="Write some comments" id="commentText-@item.ID"></textarea>*@
        <div class="Input_Foot" id="Input_Foot-@Model">
            <a class="imgBtn" id="imgBtn-@Model" onclick="imgBtnClick('@Model')">'◡'</a><span class="locationBtn"><i class="glyphicon glyphicon-map-marker"></i><a id="CurrentAddress"></a></span><a class="postBtn" onclick="publishNote('@Model')">确定</a>
        </div>
    </div>
    <div class="faceDiv" id="faceDiv-@Model">
        <section class="emoji_container" id="emoji_container-@Model"></section>
        <section class="emoji_tab" id="emoji_tab-@Model"></section>
    </div>
</div>
<script type="text/javascript">
    window.onload = function () {       
        $("#CurrentAddress").html(getLocation());
    }
</script>

LPlus/src/LPlus/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

LPlus/src/LPlus/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LPlus/src/LPlus/Views/Shared/Components/ContactList/Default.cshtml
@using Model.User
@using LPlus.HtmlHelper
@model List<UserModel>

@Html.ContactList(Model)

LPlus/src/LPlus/Views/Shared/Components/Menu/Default.cshtml
@using Microsoft.AspNetCore.Http
@using Model.Menu
@using LPlus.HtmlHelper
@model List<MenuModel>

@inject IHttpContextAccessor context

@Html.Menu(Model, context)

LPlus/src/LPlus/Views/Shared/_ContactList.cshtml
<div class="tab-pane" id="contactmenu">
    <div class="input-group input-search-contact">
        <input type="text" class="form-control" placeholder="Search contact">
        <span class="input-group-btn">
            <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
        </span>
    </div>
    <h5 class="sidebar-title">My Contacts</h5>
    @await Component.InvokeAsync("ContactList")
</div><!-- tab-pane -->

LPlus/src/LPlus/Views/Shared/_EmailMenu.cshtml
<div class="tab-pane" id="emailmenu">
    <div class="sidebar-btn-wrapper">
        <a href="compose.html" class="btn btn-danger btn-block">Compose</a>
    </div>
    <h5 class="sidebar-title">Mailboxes</h5>
    <ul class="nav nav-pills nav-stacked nav-quirk nav-mail">
        <li><a href="email.html"><i class="fa fa-inbox"></i> <span>Inbox (3)</span></a></li>
        <li><a href="email.html"><i class="fa fa-pencil"></i> <span>Draft (2)</span></a></li>
        <li><a href="email.html"><i class="fa fa-paper-plane"></i> <span>Sent</span></a></li>
    </ul>
    <h5 class="sidebar-title">Tags</h5>
    <ul class="nav nav-pills nav-stacked nav-quirk nav-label">
        <li><a href="#"><i class="fa fa-tags primary"></i> <span>Communication</span></a></li>
        <li><a href="#"><i class="fa fa-tags success"></i> <span>Updates</span></a></li>
        <li><a href="#"><i class="fa fa-tags warning"></i> <span>Promotions</span></a></li>
        <li><a href="#"><i class="fa fa-tags danger"></i> <span>Social</span></a></li>
    </ul>
</div><!-- tab-pane -->

LPlus/src/LPlus/Views/Shared/_Menu.cshtml
<div class="tab-pane active" id="mainmenu">
    <ul class="nav nav-pills nav-stacked nav-quirk">
        @await Component.InvokeAsync("Menu")
    </ul>
</div><!-- tab-pane -->